remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme

title: "Dev Handbook"
description: "My development and system administration handbook"
url: "https://rstream.github.io"
baseurl: "/dev-handbook"

markdown: kramdown
kramdown:
  input: GFM